import { Component, computed, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { AuthService } from '../core/auth.service';
import { AddressService } from '../core/address.service';
import { ImageUploadService } from '../core/image-upload.service';
import { Address } from '../core/models';

@Component({selector:'app-orders',imports:[RouterLink],template:`<section class="subpage"><p class="eyebrow">HISTORIQUE</p><h1>Mes commandes</h1><div class="empty-state"><h2>Ta première commande t’attend.</h2><p>Aucune commande enregistrée pour le moment.</p><a routerLink="/commander" class="button">Commander</a></div></section>`})
export class OrdersComponent{}

@Component({selector:'app-addresses',imports:[ReactiveFormsModule],template:`
<section class="subpage addresses-page"><div class="addresses-title"><div><p class="eyebrow">LIVRAISON</p><h1>Mes adresses</h1></div><button class="button" (click)="openNew()">Ajouter</button></div>
@if(addresses.loading()){<p>Chargement des adresses…</p>}@else if(addresses.error()){<p class="form-error">{{addresses.error()}}</p>}@else if(!addresses.addresses().length){<div class="empty-state"><h2>Aucune adresse enregistrée.</h2><p>Ajoute une adresse pour préparer ta prochaine livraison.</p><button class="button" (click)="openNew()">Ajouter une adresse</button></div>}@else{<div class="address-list">@for(address of addresses.addresses();track address.id){<article class="address-card"><div>@if(address.primary){<span>PRINCIPALE</span>}<h2>{{address.label}}</h2><p>{{address.firstName}} {{address.lastName}}<br>{{address.line1}}@if(address.line2){<br>{{address.line2}}}<br>{{address.postalCode}} {{address.city}}<br>{{address.phone}}</p>@if(address.instructions){<small>{{address.instructions}}</small>}</div><div class="address-actions"><button class="text-button" (click)="edit(address)">Modifier</button>@if(!address.primary){<button class="text-button" (click)="makePrimary(address)">Définir principale</button>}<button class="text-button danger" (click)="remove(address)">Supprimer</button></div></article>}</div>}
@if(editorOpen()){<div class="address-modal-backdrop" (click)="close()"></div><aside class="address-modal" role="dialog" aria-modal="true" aria-labelledby="address-title"><div class="drawer-head"><h2 id="address-title">{{editingId()?'Modifier l’adresse':'Nouvelle adresse'}}</h2><button class="icon-button" (click)="close()" aria-label="Fermer">×</button></div><form [formGroup]="addressForm" (ngSubmit)="saveAddress()">
<fieldset class="address-type"><legend>Où est-ce qu’on te livre ? *</legend><div class="address-type-options"><button type="button" [class.selected]="addressType()==='home'" [attr.aria-pressed]="addressType()==='home'" (click)="chooseType('home')">Chez moi</button><button type="button" [class.selected]="addressType()==='work'" [attr.aria-pressed]="addressType()==='work'" (click)="chooseType('work')">Au travail</button><button type="button" [class.selected]="addressType()==='other'" [attr.aria-pressed]="addressType()==='other'" (click)="chooseType('other')">Autre</button></div>@if(addressType()==='other'){<label class="custom-address-label">Nom personnalisé *<input formControlName="label" placeholder="Chez Mariame, Salle de sport..."></label>}</fieldset>
<div class="form-row"><label>Prénom *<input formControlName="firstName"></label><label>Nom *<input formControlName="lastName"></label></div><label>Téléphone *<input type="tel" formControlName="phone"></label><label>Adresse *<input formControlName="line1"></label><label>Complément<input formControlName="line2"></label><div class="form-row"><label>Ville *<input formControlName="city"></label><label>Code postal *<input formControlName="postalCode"></label></div><label>Instructions de livraison<textarea rows="2" formControlName="instructions"></textarea></label><label class="checkbox"><input type="checkbox" formControlName="primary"> Définir comme adresse principale</label>@if(actionError()){<p class="form-error">{{actionError()}}</p>}<button class="button full" [disabled]="addressForm.invalid||saving()">{{saving()?'Enregistrement…':'Enregistrer l’adresse'}}</button></form></aside>}</section>`})
export class AddressesComponent {
  readonly addresses=inject(AddressService); private auth=inject(AuthService); private fb=inject(FormBuilder);
  readonly editorOpen=signal(false); readonly editingId=signal<string|null>(null); readonly saving=signal(false); readonly actionError=signal(''); readonly addressType=signal<'home'|'work'|'other'>('home');
  readonly addressForm=this.fb.group({label:['Chez moi',Validators.required],firstName:['',Validators.required],lastName:['',Validators.required],phone:['',Validators.required],line1:['',Validators.required],line2:[''],city:['',Validators.required],postalCode:['',Validators.required],instructions:[''],primary:[false]});
  chooseType(type:'home'|'work'|'other'){this.addressType.set(type);this.addressForm.controls.label.setValue(type==='home'?'Chez moi':type==='work'?'Au travail':'');}
  openNew(){const user=this.auth.user();this.editingId.set(null);this.addressType.set('home');this.addressForm.reset({label:'Chez moi',firstName:user?.firstName??'',lastName:user?.lastName??'',phone:user?.phone??'',line1:'',line2:'',city:'',postalCode:'',instructions:'',primary:false});this.editorOpen.set(true)}
  edit(address:Address){this.editingId.set(address.id??null);const normalized=address.label.toLowerCase();const type=normalized==='chez moi'||normalized==='maison'?'home':normalized==='au travail'||normalized==='travail'?'work':'other';this.addressType.set(type);this.addressForm.reset({label:type==='home'?'Chez moi':type==='work'?'Au travail':address.label,firstName:address.firstName,lastName:address.lastName,phone:address.phone,line1:address.line1,line2:address.line2??'',city:address.city,postalCode:address.postalCode,instructions:address.instructions??'',primary:address.primary??false});this.editorOpen.set(true)}
  close(){this.editorOpen.set(false);this.actionError.set('')}
  async saveAddress(){if(this.addressForm.invalid)return;this.saving.set(true);this.actionError.set('');const value=this.addressForm.getRawValue();const address={label:value.label??'',firstName:value.firstName??'',lastName:value.lastName??'',phone:value.phone??'',line1:value.line1??'',line2:value.line2??'',city:value.city??'',postalCode:value.postalCode??'',instructions:value.instructions??'',primary:value.primary??false};try{const id=this.editingId();if(id){await this.addresses.update(id,address);if(address.primary)await this.addresses.setPrimary(id)}else{const created=await this.addresses.create(address);if(address.primary)await this.addresses.setPrimary(created.id)}this.close()}catch{this.actionError.set('Impossible d’enregistrer cette adresse.')}finally{this.saving.set(false)}}
  async makePrimary(address:Address){if(address.id)await this.addresses.setPrimary(address.id)}
  async remove(address:Address){if(!address.id||!confirm(`Supprimer l’adresse « ${address.label} » ?`))return;try{await this.addresses.remove(address.id)}catch{this.actionError.set('Impossible de supprimer cette adresse.')}}
}

@Component({selector:'app-profile',imports:[ReactiveFormsModule],template:`
<section class="subpage profile-page"><p class="eyebrow">PROFIL</p><h1>Mes informations</h1>
<section class="profile-photo-card" aria-labelledby="profile-photo-title">
  <div class="profile-avatar">@if(displayPhoto()){<img [src]="displayPhoto()" alt="Photo de profil">}@else{<span>{{initials()}}</span>}</div>
  <div class="profile-photo-copy"><h2 id="profile-photo-title">Photo de profil</h2><p>Une photo carrée fonctionne le mieux. JPEG, PNG ou WebP, 5 Mo maximum.</p>
    <div class="profile-photo-actions"><label class="button ghost" for="profile-photo-input">{{auth.user()?.photoURL?'Remplacer':'Ajouter une photo'}}</label>@if(auth.user()?.photoURL){<button type="button" class="text-button danger" [disabled]="photoUploading()" (click)="removePhoto()">Supprimer</button>}</div>
    <input id="profile-photo-input" class="profile-photo-input" type="file" accept="image/jpeg,image/png,image/webp" [disabled]="photoUploading()" (change)="onPhotoSelected($event)">
    @if(photoUploading()){<div class="profile-upload-progress" role="status"><span [style.width.%]="photoProgress()"></span></div><small>Envoi de la photo… {{photoProgress()}} %</small>}
    @if(photoError()){<p class="form-error">{{photoError()}}</p>}
  </div>
</section>
<form class="profile-form" [formGroup]="form" (ngSubmit)="save()"><div class="form-row"><label>Prénom *<input formControlName="firstName"></label><label>Nom *<input formControlName="lastName"></label></div><label>Email Google<input [value]="auth.user()?.email" disabled></label><label>Téléphone *<input type="tel" formControlName="phone"></label><label>Date de naissance *<input type="date" formControlName="birthDate"></label><div class="form-row"><label>Allergies *<textarea rows="3" formControlName="allergies"></textarea></label><label>Intolérances *<textarea rows="3" formControlName="intolerances"></textarea></label></div><p class="form-note">Vérifie toujours les allergènes indiqués sur chaque fiche produit.</p>@if(saved()){<p class="success">Tes informations sont enregistrées.</p>}@if(error()){<p class="form-error">{{error()}}</p>}<button class="button" [disabled]="form.invalid||saving()">{{saving()?'Enregistrement…':'Enregistrer'}}</button></form></section>`})
export class ProfileComponent{
  readonly auth=inject(AuthService);private fb=inject(FormBuilder);private images=inject(ImageUploadService);
  readonly saving=signal(false);readonly saved=signal(false);readonly error=signal('');readonly photoUploading=signal(false);readonly photoProgress=signal(0);readonly photoError=signal('');readonly photoPreview=signal('');readonly displayPhoto=computed(()=>this.photoPreview()||this.auth.user()?.photoURL||'');
  private user=this.auth.user();readonly form=this.fb.group({firstName:[this.user?.firstName??'',Validators.required],lastName:[this.user?.lastName??'',Validators.required],phone:[this.user?.phone??'',Validators.required],birthDate:[this.user?.birthDate??'',Validators.required],allergies:[this.user?.allergies?.join(', ')??'',Validators.required],intolerances:[this.user?.intolerances?.join(', ')??'',Validators.required]});
  initials(){const user=this.auth.user();return`${user?.firstName?.[0]??''}${user?.lastName?.[0]??''}`.toUpperCase()||'MK'}
  async onPhotoSelected(event:Event){const input=event.target as HTMLInputElement;const file=input.files?.[0];input.value='';if(!file)return;const previousPath=this.auth.user()?.photoPath;const preview=URL.createObjectURL(file);this.photoPreview.set(preview);this.photoUploading.set(true);this.photoProgress.set(0);this.photoError.set('');let uploaded:{url:string;path:string}|undefined;try{uploaded=await this.images.uploadProfile(file,progress=>this.photoProgress.set(progress));await this.auth.updateProfilePhoto(uploaded.url,uploaded.path);this.photoPreview.set('');if(previousPath&&previousPath!==uploaded.path){try{await this.images.removePath(previousPath)}catch{}}}catch(error){this.photoPreview.set('');if(uploaded){try{await this.images.removePath(uploaded.path)}catch{}}this.photoError.set(error instanceof Error&&error.message==='FORMAT'?'Choisis une image JPEG, PNG ou WebP.':error instanceof Error&&error.message==='SIZE'?'La photo ne doit pas dépasser 5 Mo.':'Impossible d’enregistrer la photo. Vérifie Firebase Storage.')}finally{URL.revokeObjectURL(preview);this.photoUploading.set(false)}}
  async removePhoto(){const oldPath=this.auth.user()?.photoPath;this.photoUploading.set(true);this.photoError.set('');try{await this.auth.removeProfilePhoto();if(oldPath){try{await this.images.removePath(oldPath)}catch{}}}catch{this.photoError.set('Impossible de supprimer la photo.')}finally{this.photoUploading.set(false)}}
  async save(){if(this.form.invalid)return;this.saving.set(true);this.saved.set(false);this.error.set('');const value=this.form.getRawValue();try{await this.auth.updateProfileDetails({firstName:value.firstName??'',lastName:value.lastName??'',phone:value.phone??'',birthDate:value.birthDate??'',allergies:this.lines(value.allergies),intolerances:this.lines(value.intolerances)});this.saved.set(true)}catch{this.error.set('Impossible d’enregistrer les modifications.')}finally{this.saving.set(false)}}private lines(value:string|null){return(value??'').split(/[,\n]/).map(item=>item.trim()).filter(Boolean)}
}
