import { Component, computed, inject } from '@angular/core';
import { CurrencyPipe, DatePipe, UpperCasePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { AuthService } from '../core/auth.service';
import { AdminOrder, OrderAdminService } from '../core/order-admin.service';
import { CustomerAdminService } from '../core/customer-admin.service';
import { displayOrderNumber } from '../core/order-number';

@Component({selector:'app-admin-dashboard-live',imports:[CurrencyPipe,DatePipe,UpperCasePipe,RouterLink],template:`
<section class="admin-page"><div class="admin-title"><div><p class="eyebrow">{{today|date:'EEEE d MMMM'|uppercase}}</p><h1>Bonjour {{auth.user()?.firstName||'Admin'}}.</h1></div><span>Données Firestore en direct</span></div>
<div class="metrics"><article><small>COMMANDES</small><strong>{{orderCount()}}</strong><span>Hors commandes annulées</span></article><article><small>CLIENTS</small><strong>{{clientCount()}}</strong><span>Comptes clients actifs</span></article><article><small>ARTICLES À CONCEVOIR</small><strong>{{itemsToPrepare()}}</strong><span>À préparer pour les livraisons</span></article><article><small>CA TOTAL</small><strong>{{totalRevenue()|currency:'EUR':'symbol':'1.0-0':'fr'}}</strong><span>Total hors commandes annulées</span></article></div>
<div class="admin-section-head"><h2>Commandes récentes</h2><a routerLink="/admin/orders">Tout voir →</a></div>@if(orders.loading()){<div class="admin-empty"><p>Chargement des commandes…</p></div>}@else if(orders.error()){<p class="form-error">{{orders.error()}}</p>}@else if(!orders.orders().length){<div class="admin-empty"><h2>Aucune commande.</h2><p>Les nouvelles commandes apparaîtront ici automatiquement.</p></div>}@else{<div class="admin-table"><div class="table-row table-head"><span>Numéro</span><span>Client</span><span>Date</span><span>Montant</span><span>Statut</span></div>@for(order of recent();track order.id){<div class="table-row"><strong>{{orderNumber(order)}}</strong><span>{{customerName(order)}}</span><span>{{order.createdAt?.toDate()|date:'dd/MM HH:mm'}}</span><strong>{{order.total||0|currency:'EUR':'symbol':'1.2-2':'fr'}}</strong><span class="status" [class]="'status '+order.status">{{statusLabel(order.status)}}</span></div>}</div>}</section>`})
export class AdminDashboardLiveComponent{readonly auth=inject(AuthService);readonly orders=inject(OrderAdminService);readonly customers=inject(CustomerAdminService);readonly today=new Date();readonly orderNumber=displayOrderNumber;readonly activeOrders=computed(()=>this.orders.orders().filter(order=>order.status!=='cancelled'));readonly orderCount=computed(()=>this.activeOrders().length);readonly clientCount=computed(()=>this.customers.customers().filter(user=>user.role==='customer'&&!user.disabled).length);readonly itemsToPrepare=computed(()=>this.orders.orders().filter(order=>['pending','confirmed','preparing'].includes(order.status??'pending')).reduce((sum,order)=>sum+(order.items??[]).reduce((itemSum,item)=>itemSum+(item.quantity??1),0),0));readonly totalRevenue=computed(()=>this.activeOrders().reduce((sum,order)=>sum+Math.max(0,(order.subtotal??order.total??0)-(order.discount??0)),0));readonly recent=computed(()=>this.orders.orders().slice(0,6));customerName(order:AdminOrder){return[order.customer?.firstName,order.customer?.lastName].filter(Boolean).join(' ')||'Client'}statusLabel(status='pending'){return({pending:'Nouvelle',confirmed:'Confirmée',preparing:'En préparation',ready:'Prête',delivering:'En livraison',completed:'Terminée',cancelled:'Annulée'} as Record<string,string>)[status]??status}}
