import { Component, inject, signal } from '@angular/core';
import { FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { AuthService } from '../core/auth.service';

@Component({selector:'app-onboarding',imports:[ReactiveFormsModule],template:`
@if(auth.needsOnboarding()){<div class="onboarding-backdrop"></div><section class="onboarding-modal" role="dialog" aria-modal="true" aria-labelledby="onboarding-title"><div class="onboarding-progress"><span [class.active]="step()===1"></span><span [class.active]="step()===2"></span></div><p class="eyebrow">PREMIÈRE CONNEXION · ÉTAPE {{step()}}/2</p><h1 id="onboarding-title">{{step()===1?'Faisons connaissance.':'Encore quelques détails.'}}</h1><p>{{step()===1?'Complète les informations que Google ne nous a pas transmises.':'Ces informations facilitent ta livraison et nous aident à mieux te servir.'}}</p><form [formGroup]="form" (ngSubmit)="save()">
@if(step()===1){<label>Email Google<input [value]="auth.user()?.email" disabled><small>Récupéré avec Google, non modifiable ici.</small></label><div class="form-row"><label>Prénom *<input formControlName="firstName" autocomplete="given-name"></label><label>Nom *<input formControlName="lastName" autocomplete="family-name"></label></div><label>Téléphone *<input formControlName="phone" type="tel" autocomplete="tel" placeholder="06 00 00 00 00"></label><label>Date de naissance *<input formControlName="birthDate" type="date" autocomplete="bday"></label><button type="button" class="button full" [disabled]="identityInvalid()" (click)="step.set(2)">Continuer</button>}
@else{<label>Adresse *<input formControlName="address" autocomplete="street-address"></label><label>Complément d’adresse<input formControlName="address2" placeholder="Bâtiment, étage, porte..."></label><div class="form-row"><label>Ville *<input formControlName="city" autocomplete="address-level2"></label><label>Code postal *<input formControlName="postalCode" autocomplete="postal-code"></label></div><label>Instructions de livraison<textarea formControlName="instructions" rows="2" placeholder="Code, interphone..."></textarea></label><div class="form-row health-fields"><label>Allergies *<textarea formControlName="allergies" rows="2" placeholder="Écris Aucune si tu n’en as pas"></textarea></label><label>Intolérances *<textarea formControlName="intolerances" rows="2" placeholder="Écris Aucune si tu n’en as pas"></textarea></label></div><p class="onboarding-warning">Ces informations ne remplacent pas la vérification des allergènes sur chaque produit.</p>@if(error()){<p class="form-error">{{error()}}</p>}<div class="onboarding-actions"><button type="button" class="button ghost" (click)="step.set(1)">Retour</button><button class="button" [disabled]="form.invalid||saving()">{{saving()?'Enregistrement…':'Terminer'}}</button></div>}
</form></section>}
`})
export class OnboardingComponent{readonly auth=inject(AuthService);private fb=inject(FormBuilder);readonly step=signal(1);readonly saving=signal(false);readonly error=signal('');readonly form=this.fb.group({firstName:[this.auth.user()?.firstName??'',Validators.required],lastName:[this.auth.user()?.lastName??'',Validators.required],phone:[this.auth.user()?.phone??'',Validators.required],birthDate:[this.auth.user()?.birthDate??'',Validators.required],address:['',Validators.required],address2:[''],city:['',Validators.required],postalCode:['',Validators.required],instructions:[''],allergies:['',Validators.required],intolerances:['',Validators.required]});identityInvalid(){return ['firstName','lastName','phone','birthDate'].some(name=>this.form.get(name)?.invalid)}async save(){if(this.form.invalid)return;this.saving.set(true);this.error.set('');const value=this.form.getRawValue();try{await this.auth.completeOnboarding({firstName:value.firstName??'',lastName:value.lastName??'',phone:value.phone??'',birthDate:value.birthDate??'',address:value.address??'',address2:value.address2??'',city:value.city??'',postalCode:value.postalCode??'',instructions:value.instructions??'',allergies:this.lines(value.allergies),intolerances:this.lines(value.intolerances)})}catch{this.error.set('Impossible d’enregistrer tes informations. Vérifie les règles Firestore puis réessaie.')}finally{this.saving.set(false)}}private lines(value:string|null){return (value??'').split(/[,\n]/).map(item=>item.trim()).filter(Boolean)}}
