import { Injectable, computed, signal } from '@angular/core';
import { createUserWithEmailAndPassword, GoogleAuthProvider, onAuthStateChanged, reload, sendEmailVerification, sendPasswordResetEmail, signInWithEmailAndPassword, signInWithPopup, signOut, User } from 'firebase/auth';
import { deleteField, doc, getDoc, serverTimestamp, setDoc } from 'firebase/firestore';
import { AppUser } from './models'; import { firebaseAuth, firestore } from './firebase';
@Injectable({ providedIn: 'root' })
export class AuthService {
  readonly user = signal<AppUser | null>(null); readonly ready = signal(false); readonly emailVerificationRequired = signal(false); readonly isAdmin = computed(() => this.user()?.role === 'admin'); readonly needsOnboarding = computed(() => { const user=this.user(); return !!user && user.onboardingComplete !== true; });
  constructor() { onAuthStateChanged(firebaseAuth, async account => { this.syncEmailVerification(account); if (!account) { this.user.set(null); this.ready.set(true); return; } const profile = await getDoc(doc(firestore, 'users', account.uid)); const appUser=profile.exists()?profile.data() as AppUser:{uid:account.uid,firstName:'',lastName:'',email:account.email??'',phone:'',role:'customer' as const}; if(appUser.disabled){this.user.set(null);this.ready.set(true);await signOut(firebaseAuth);return;} this.user.set(appUser); this.ready.set(true); }); }
  async signIn(email: string, password: string) { const credential=await signInWithEmailAndPassword(firebaseAuth, email, password);this.syncEmailVerification(credential.user); }
  async signUp(data: Partial<AppUser> & { password: string }) { const credential = await createUserWithEmailAndPassword(firebaseAuth, data.email ?? '', data.password); const profile: AppUser = { uid: credential.user.uid, firstName: data.firstName ?? '', lastName: data.lastName ?? '', email: data.email ?? '', phone: data.phone ?? '', birthDate: data.birthDate, role: 'customer', onboardingComplete: false }; await setDoc(doc(firestore, 'users', credential.user.uid), { ...profile, createdAt: serverTimestamp() }); this.user.set(profile); this.syncEmailVerification(credential.user); await this.sendVerificationEmail(); }
  async signInWithGoogle() { const credential = await signInWithPopup(firebaseAuth, new GoogleAuthProvider()); const profileRef = doc(firestore, 'users', credential.user.uid); const existing = await getDoc(profileRef); if (!existing.exists()) { const names = (credential.user.displayName ?? '').trim().split(/\s+/); const profile: AppUser = { uid: credential.user.uid, firstName: names[0] ?? '', lastName: names.slice(1).join(' '), email: credential.user.email ?? '', phone: credential.user.phoneNumber ?? '', role: 'customer', onboardingComplete: false }; if(credential.user.photoURL)profile.photoURL=credential.user.photoURL; await setDoc(profileRef, { ...profile, createdAt: serverTimestamp() }); this.user.set(profile); } }
  async completeOnboarding(data: { firstName:string; lastName:string; phone:string; birthDate:string; allergies:string[]; intolerances:string[]; address:string; address2:string; city:string; postalCode:string; instructions:string }) { const current=this.user(); if(!current)return; const profile:AppUser={...current,firstName:data.firstName,lastName:data.lastName,phone:data.phone,birthDate:data.birthDate,allergies:data.allergies,intolerances:data.intolerances,onboardingComplete:true}; await setDoc(doc(firestore,'users',current.uid),{...profile,updatedAt:serverTimestamp()},{merge:true}); await setDoc(doc(firestore,'addresses',`${current.uid}-primary`),{userId:current.uid,label:'Maison',firstName:data.firstName,lastName:data.lastName,phone:data.phone,line1:data.address,line2:data.address2,city:data.city,postalCode:data.postalCode,instructions:data.instructions,primary:true,updatedAt:serverTimestamp()},{merge:true}); this.user.set(profile); }
  async updateProfileDetails(data: Pick<AppUser,'firstName'|'lastName'|'phone'|'birthDate'|'allergies'|'intolerances'>) { const current=this.user(); if(!current)return; const profile={...current,...data}; await setDoc(doc(firestore,'users',current.uid),{...data,updatedAt:serverTimestamp()},{merge:true}); this.user.set(profile); }
  async updateProfilePhoto(photoURL:string,photoPath:string){const current=this.user();if(!current)throw new Error('AUTH_REQUIRED');await setDoc(doc(firestore,'users',current.uid),{photoURL,photoPath,updatedAt:serverTimestamp()},{merge:true});this.user.set({...current,photoURL,photoPath})}
  async removeProfilePhoto(){const current=this.user();if(!current)return;await setDoc(doc(firestore,'users',current.uid),{photoURL:deleteField(),photoPath:deleteField(),updatedAt:serverTimestamp()},{merge:true});const {photoURL:_photoURL,photoPath:_photoPath,...profile}=current;this.user.set(profile)}
  resetPassword(email: string) { return sendPasswordResetEmail(firebaseAuth, email); }
  async sendVerificationEmail() { const account=firebaseAuth.currentUser;if(!account||!this.isPasswordAccount(account)||account.emailVerified)return;await sendEmailVerification(account,{url:`${window.location.origin}/connexion?emailVerifie=1`}); }
  async refreshEmailVerification() { const account=firebaseAuth.currentUser;if(!account)return false;await reload(account);if(account.emailVerified)await account.getIdToken(true);this.syncEmailVerification(account);return !this.emailVerificationRequired(); }
  signOut() { return signOut(firebaseAuth); }
  private isPasswordAccount(account:User){return account.providerData.some(provider=>provider.providerId==='password')}
  private syncEmailVerification(account:User|null){this.emailVerificationRequired.set(!!account&&this.isPasswordAccount(account)&&!account.emailVerified)}
}
